version: "3.9"
services:
  postgres:
    image: postgres:14.6
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PGSQL_DB}
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASS}
    ports:
      - ${PGSQL_PORT}:${PGSQL_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
