version: "3.9"
services:
  postgres:
    image: postgres:14.5-bullseye
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PGSQL_DB}
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASS}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: